### ISSUE TITLE
Can't clone testdata using macOS and an APFS file system

### ISSUE THREAD

**Issue by salevajo** [liquidinvestigations/hoover-testdata#2]
```
$ git clone git@github.com:hoover/testdata.git
Cloning into 'testdata'...
remote: Counting objects: 276, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 276 (delta 0), reused 4 (delta 0), pack-reused 270
Receiving objects: 100% (276/276), 9.17 MiB | 5.74 MiB/s, done.
Resolving deltas: 100% (66/66), done.
error: unable to create file data/disk-files/bad-filename/modifi�.txt: Illegal byte sequence
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

See https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html
> While both filesystems expect filenames to be encoded in UTF-8, APFS stores filenames on disk in UTF-8 encoding, whereas HFS stores filenames on disk in UTF-16 encoding.
APFS doesn’t allow files to be created with filenames that contain unassigned codepoints in the Unicode 9.0 standard, whereas HFS+ does.

**Comment by kappuchino** [comment]
I get around it by using a dmg container without APFS. Do I understand that correctly that this is a MacOS / Git Issue and not one related to Test Lib?

**Comment by salevajo** [comment]
Yes, that's the case.
